# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master", "try-yarn" ]
  pull_request:
    branches: [ "master", "try_yarn"]

jobs:
  build:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
#      run: cd ./angular && npm ci
      run: cd ./angular && yarn install --frozen-lockfile --check-files #--modules-folder /home/runner/work/angular-react-starter/angular


    - name: install/upgrade xvfb 
      run: /usr/bin/sudo apt-get install -y xvfb


    - name: start yarn test with Xvfb
      run: cd ./angular && /usr/bin/xvfb-run yarn test #--auto-servernum yarn test


    - name: build the app
      run: cd ./angular && yarn run
#      run: cd ./angular && pwd && npm run build --verbose


#    - name: Run headless test
 #     uses: GabrielBB/xvfb-action@v1.6
   #   with:
   #     working-directory: ./angular
      #  run: yarn test
        
        


    

